Repository B3-3iL-DLW/3il-student, pull requests merged in 2024-03, with the labels that each got.

#4 🐛: fix retrieval of data
  backend/src/Controller/Api/TimetableController.php
  backend/src/Service/ClassesScraperService.php
  backend/src/Service/TimetableService.php
Labels: bug

#5 📝🔧: added env variables to api and readme for documentation
  .gitignore
  .vscode/settings.json
  README.md
  backend/.env
  backend/README.md
  backend/composer.json
  backend/config/services.yaml
  backend/src/Controller/Api/ClassesController.php
  backend/src/Controller/Api/TimetableController.php
  backend/src/Service/ClassesScraperService.php
  backend/src/Service/TimetableService.php
  frontend/app_student/.fvmrc
  frontend/app_student/.gitignore
  frontend/app_student/.vscode/settings.json
Labels: documentation

#15 Feat/create data layer and repo for api
  .idea/.gitignore
  .idea/3il-student.iml
  .idea/discord.xml
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .vscode/launch.json
  backend/composer.json
  backend/composer.lock
  backend/config/bundles.php
  backend/config/packages/debug.yaml
  backend/symfony.lock
  frontend/app_student/.run/main_dev.run.xml
  frontend/app_student/.run/main_prod.run.xml
  frontend/app_student/lib/api/api_service.dart
  frontend/app_student/lib/api/classes/entities/class.dart
  frontend/app_student/lib/api/classes/repositories/class_repository.dart
  frontend/app_student/lib/api/courses/entities/course.dart
  frontend/app_student/lib/api/day_schedule/entities/day_schedule.dart
  frontend/app_student/lib/api/day_schedule/repositories/day_schedule.dart
  frontend/app_student/lib/classes/bloc/class_bloc.dart
  frontend/app_student/lib/classes/views/class.dart
  frontend/app_student/lib/config/config.dart
  frontend/app_student/lib/config/dev_config.dart
  frontend/app_student/lib/config/prod_config.dart
  frontend/app_student/lib/day_schedules/bloc/day_schedule_bloc.dart
  frontend/app_student/lib/day_schedules/views/day_schedule.dart
  frontend/app_student/lib/main.dart
  frontend/app_student/lib/main_dev.dart
  frontend/app_student/lib/main_prod.dart
  frontend/app_student/pubspec.lock
  frontend/app_student/pubspec.yaml
  frontend/app_student/test/widget_test.dart
Labels: enhancement

#17 UI/create login page
  .vscode/launch.json
  frontend/app_student/.gitignore
  frontend/app_student/assets/images/3il-logo.jpg
  frontend/app_student/lib/config/prod_config.dart
  frontend/app_student/lib/generated/assets.dart
  frontend/app_student/lib/login/views/login_page.dart
  frontend/app_student/lib/login/widgets/form/button_submit.dart
  frontend/app_student/lib/login/widgets/form/form_login.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_birthdate.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_ine.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_prenom.dart
  frontend/app_student/lib/login/widgets/header/header_logo.dart
  frontend/app_student/lib/login/widgets/header/header_text.dart
  frontend/app_student/lib/main_dev.dart
  frontend/app_student/lib/main_prod.dart
  frontend/app_student/pubspec.yaml
Labels: enhancement

#24 Ci/setup linter
  .github/workflows/deploy-backend-dev.yml
  .github/workflows/execute-linter-front.yml
  backend/.gitignore
  backend/.php-cs-fixer.dist.php
  backend/README.md
  backend/composer.json
  backend/composer.lock
  backend/src/Controller/Api/ClassesController.php
  backend/src/Controller/Api/TimetableController.php
  backend/src/Entity/EventHours.php
  backend/src/Entity/WeekSchedule.php
  backend/src/Service/ClassesScraperService.php
  backend/src/Service/JsonService.php
  backend/src/Service/TimetableService.php
  backend/src/Service/XMLService.php
  backend/symfony.lock
  frontend/app_student/analysis_options.yaml
  frontend/app_student/devtools_options.yaml
  frontend/app_student/lib/classes/bloc/class_bloc.dart
  frontend/app_student/lib/classes/views/class.dart
  frontend/app_student/lib/login/views/login_page.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_prenom.dart
Labels: documentation, enhancement

#25 Refactor/refactor data layer api
  frontend/app_student/lib/api/api_service.dart
  frontend/app_student/lib/api/class_groups/entities/class_group_entity.dart
  frontend/app_student/lib/api/class_groups/models/class_group_model.dart
  frontend/app_student/lib/api/class_groups/repositories/class_group_repository.dart
  frontend/app_student/lib/api/classes/entities/class.dart
  frontend/app_student/lib/api/classes/repositories/class_repository.dart
  frontend/app_student/lib/api/courses/entities/course.dart
  frontend/app_student/lib/api/day_schedule/entities/day_schedule.dart
  frontend/app_student/lib/api/day_schedule/entities/day_schedule_entity.dart
  frontend/app_student/lib/api/day_schedule/models/day_schedule_model.dart
  frontend/app_student/lib/api/day_schedule/repositories/day_schedule.dart
  frontend/app_student/lib/api/event_hours/entities/event_hours_entity.dart
  frontend/app_student/lib/api/event_hours/models/event_hours_model.dart
  frontend/app_student/lib/api/events/entities/event_entity.dart
  frontend/app_student/lib/api/events/models/event_model.dart
  frontend/app_student/lib/api/users/entities/user_entity.dart
  frontend/app_student/lib/api/users/models/user_model.dart
  frontend/app_student/lib/api/week_schedule/entities/week_schedule_entity.dart
  frontend/app_student/lib/api/week_schedule/models/week_schedule_model.dart
  frontend/app_student/lib/api/week_schedule/repositories/week_schedule_repositories.dart
  frontend/app_student/lib/class_groups/cubit/class_group_cubit.dart
  frontend/app_student/lib/class_groups/cubit/class_group_state.dart
  frontend/app_student/lib/class_groups/views/class_group_view.dart
  frontend/app_student/lib/classes/bloc/class_bloc.dart
  frontend/app_student/lib/classes/views/class.dart
  frontend/app_student/lib/day_schedules/bloc/day_schedule_bloc.dart
  frontend/app_student/lib/day_schedules/views/day_schedule.dart
  frontend/app_student/lib/generated/assets.dart
  frontend/app_student/lib/main_dev.dart
  frontend/app_student/lib/week_schedule/cubit/week_schedule_cubit.dart
  frontend/app_student/lib/week_schedule/cubit/week_schedule_state.dart
  frontend/app_student/lib/week_schedule/views/week_schedule.dart
  frontend/app_student/pubspec.lock
  frontend/app_student/pubspec.yaml
Labels: enhancement

#37 Feat/translations l10n
  .gitignore
  backend/.php-cs-fixer.cache
  frontend/app_student/README.md
  frontend/app_student/l10n.yaml
  frontend/app_student/lib/class_groups/views/class_group_page.dart
  frontend/app_student/lib/l10n/app_fr.arb
  frontend/app_student/lib/login/views/login_page.dart
  frontend/app_student/lib/login/widgets/form/button_submit.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_birthdate.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_ine.dart
  frontend/app_student/lib/login/widgets/form/inputs/input_prenom.dart
  frontend/app_student/lib/login/widgets/header/header_logo.dart
  frontend/app_student/lib/login/widgets/header/header_text.dart
  frontend/app_student/lib/main_dev.dart
  frontend/app_student/pubspec.lock
  frontend/app_student/pubspec.yaml
Labels: documentation, enhancement

#38 Feat/app env vars
  frontend/app_student/.env.dist
  frontend/app_student/.gitignore
  frontend/app_student/README.md
  frontend/app_student/lib/config/dev_config.dart
  frontend/app_student/lib/config/prod_config.dart
  frontend/app_student/lib/main_dev.dart
  frontend/app_student/pubspec.lock
  frontend/app_student/pubspec.yaml
Labels: documentation, enhancement
